package main

import (
	"log"
	"os"
	"path"
	"time"
)

func main() {
	// Get command line flags.
	flags := GetFlags()

	// Create logs file.
	logsFileName := path.Join(flags.LogsDirPath, time.Now().Format(time.RFC3339))

	logsFile, err := os.Create(logsFileName)
	if err != nil {
		log.Fatalln(err)
	}
	defer logsFile.Close()

	// Create logger, the output generated by it will be
	// stored to the logs file.
	logger := NewLogger(logsFile)

	// Load configuration.
	config, err := LoadConfig(flags.ConfigPath)
	if err != nil {
		log.Fatalln("failed loading config")
	}

	_ = config

	logger.Info("app starts")
	logger.Info("app ends")
}
