package main

import (
	"github.com/Edwing123/udem-chat-app/pkg/images/profile"
	"github.com/gofiber/fiber/v2/middleware/session"
	"golang.org/x/exp/slog"
)

type Global struct {
	Logger         *slog.Logger
	Store          *session.Store
	ProfileManager *profile.Manager
}

// ConnectionDetails represents the information
// needed to connect to database server.
type ConnectionDetails struct {
	User     string `json:"user"`
	Password string `json:"password"`
	Port     uint16 `json:"port"`
	Host     string `json:"host"`
}

// Config represents the configuration file.
type Config struct {
	// Redis connection details.
	Redis ConnectionDetails `json:"redis"`

	// Database connection details.
	Database ConnectionDetails `json:"database"`

	// Server options.
	Server struct {
		// The address where the HTTP will listen on.
		Addr string
	} `json:"server"`

	// Directory where data generated by the API
	// will be stored.
	AppData string `json:"appdata"`
}

// Flags represents the command line flags passed
// to the executable.
type Flags struct {
	ConfigPath string // Path of the configuration file.
}
